-- phpMyAdmin SQL Dump
-- version 5.0.4
-- https://www.phpmyadmin.net/
--
-- Vært: 127.0.0.1
-- Genereringstid: 10. 01 2021 kl. 22:54:53
-- Serverversion: 10.4.16-MariaDB
-- PHP-version: 7.4.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `hanselandpetal`
--

-- --------------------------------------------------------

--
-- Struktur-dump for tabellen `arrangements`
--

CREATE TABLE `arrangements` (
  `id` smallint(5) UNSIGNED NOT NULL,
  `image` varchar(50) NOT NULL,
  `alt` varchar(60) NOT NULL,
  `title` varchar(100) NOT NULL,
  `price` decimal(5,2) NOT NULL,
  `description` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Data dump for tabellen `arrangements`
--

INSERT INTO `arrangements` (`id`, `image`, `alt`, `title`, `price`, `description`) VALUES
(1, '200_arrangement_yellow_tulip.jpg', 'Yellow Tulips', 'Burst of Yellow', '19.95', '<p>This simple, yet stunning arrangement brims with exuberance. Yellow tulips in a contrasting container.</p>\r\n<p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pulvinar arcu pulvinar, dictum turpis vel, semper risus. Curabitur ac augue et felis tempor molestie. Fusce ligula libero, dignissim eget ultrices ut, varius sit amet massa. Curabitur luctus nulla non lacus malesuada, eget elementum arcu lacinia. Fusce et metus non nulla sodales hendrerit. Aenean vitae enim nunc. Integer ultrices erat ac nunc commodo, in mattis mi viverra. Nullam et vehicula orci.</p>\r\n<p>Sed accumsan, odio at vestibulum viverra, magna magna cursus mi, a venenatis nibh enim sagittis felis. Suspendisse elit tortor, dictum a est in, sollicitudin laoreet purus. Nullam quis porta tortor. Suspendisse potenti. Suspendisse commodo pulvinar arcu nec fringilla. Pellentesque dignissim scelerisque elit, nec sollicitudin turpis sodales ut. Sed eget elementum augue, non dapibus dui. Aenean non rhoncus nisi. Fusce non sem suscipit, posuere risus et, adipiscing ante. Maecenas nec neque ac urna bibendum viverra eu a eros. Maecenas quis eros a lorem blandit euismod sit amet venenatis leo. Praesent a justo ut turpis tristique volutpat. Sed volutpat felis eget enim laoreet, ac porttitor eros interdum.</p>'),
(2, '200_arrangement_163066655.jpg', 'Mixed Mums', 'Polka Dot Pail', '25.95', '<p>Mum\'s the word. She\'ll go dotty over this arrangement of mixed crysanthemums in a rad pail with white polka dots.</p>\n<p>\n<p>Praesent sit amet tempus metus. In porttitor rhoncus arcu eget blandit. Cras sagittis, dolor ut lacinia tempus, lectus nunc varius augue, ut pellentesque ante libero a justo. Donec non eros dui. Curabitur a dapibus enim. Nam fermentum, turpis ac laoreet rhoncus, arcu est accumsan est, a condimentum ligula nisl quis augue. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce ut hendrerit tellus, ac aliquet arcu.</p>\n<p>Praesent volutpat, mauris vitae feugiat ullamcorper, quam neque tristique risus, rhoncus tempus tellus metus imperdiet tellus. Duis dolor diam, posuere fermentum est in, convallis condimentum nisl. Suspendisse a nisl vitae velit accumsan pretium sed at quam. Aliquam tincidunt in odio in scelerisque.</p>'),
(3, '200_tulips_daffodils_139756476.jpg', 'Mixed Tulips', 'Green Thumb', '22.95', '<p>You can tell spring\'s in the air when the daffodils and tulips are in full bloom. Blow away your winter blues with this fresh arrangement.</p>\r\n<p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pulvinar arcu pulvinar, dictum turpis vel, semper risus. Curabitur ac augue et felis tempor molestie. Fusce ligula libero, dignissim eget ultrices ut, varius sit amet massa. Curabitur luctus nulla non lacus malesuada, eget elementum arcu lacinia. Fusce et metus non nulla sodales hendrerit. Aenean vitae enim nunc. Integer ultrices erat ac nunc commodo, in mattis mi viverra. Nullam et vehicula orci.</p>\r\n<p>Sed accumsan, odio at vestibulum viverra, magna magna cursus mi, a venenatis nibh enim sagittis felis. Suspendisse elit tortor, dictum a est in, sollicitudin laoreet purus. Nullam quis porta tortor. Suspendisse potenti. Suspendisse commodo pulvinar arcu nec fringilla. Pellentesque dignissim scelerisque elit, nec sollicitudin turpis sodales ut. Sed eget elementum augue, non dapibus dui. Aenean non rhoncus nisi.</p>'),
(4, '200_bouquet_watering_can_orange_163066621.jpg', 'Watering Can with Mums', 'It\'s Raining Flowers', '19.95', '<p>April showers or autumn downpours won\'t dampen your spirits with this arrangement in a bright, orange watering can. Fill it with tulips and daffs in spring, or crystanthemums in late summer and autumn.</p>\r\n<p> Nulla faucibus, est a interdum volutpat, sem neque interdum dui, aliquam accumsan velit sapien nec purus. Integer quis massa vel odio viverra molestie. Duis rhoncus posuere felis. Proin lobortis feugiat dui, eget posuere mauris aliquet ut. Integer sagittis lacinia varius. Aenean sit amet nunc mauris. Aenean sed lobortis justo, non pharetra justo.</p>\r\n<p>Ut lobortis elit ut lectus pretium blandit. In hac habitasse platea dictumst. Quisque euismod sit amet augue non malesuada. Etiam accumsan id tellus sed ullamcorper. Vivamus eros urna, auctor id pellentesque a, feugiat at dui. Vivamus sagittis porttitor euismod. Fusce vitae ante quis orci posuere aliquam. Nullam cursus erat eu vehicula volutpat. Maecenas ut magna risus. Nunc eu eleifend massa.</p> '),
(5, '200_carnations_basket_92246977.jpg', 'Basket of Carnations', 'Get Well Soon', '19.95', '<p>What better way to lift the spirits of someone feeling under the weather than with this wicker basket filled with flowers. This example is filled with carnations, but choose the patient\'s favorite flowers to say \"Get well soon.\"</p>\r\n<p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pulvinar arcu pulvinar, dictum turpis vel, semper risus. Curabitur ac augue et felis tempor molestie. Fusce ligula libero, dignissim eget ultrices ut, varius sit amet massa. Curabitur luctus nulla non lacus malesuada, eget elementum arcu lacinia. Fusce et metus non nulla sodales hendrerit. Aenean vitae enim nunc. Integer ultrices erat ac nunc commodo, in mattis mi viverra. Nullam et vehicula orci.</p>\r\n<p>Sed accumsan, odio at vestibulum viverra, magna magna cursus mi, a venenatis nibh enim sagittis felis. Suspendisse elit tortor, dictum a est in, sollicitudin laoreet purus. Nullam quis porta tortor. Suspendisse potenti. Suspendisse commodo pulvinar arcu nec fringilla.</p>'),
(6, '200_lilacs_tulips_157045915.jpg', 'Tulips and Lilac', 'Bon Anniversaire!', '25.95', '<p>Say happy birthday to that special woman in your life with this pretty pink arrangement of lilac and tulips. It comes in a white container all wrapped up with a pink bow.</p>\r\n<p>Curabitur a dapibus enim. Nam fermentum, turpis ac laoreet rhoncus, arcu est accumsan est, a condimentum ligula nisl quis augue. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce ut hendrerit tellus, ac aliquet arcu. Praesent volutpat, mauris vitae feugiat ullamcorper, quam neque tristique risus, rhoncus tempus tellus metus imperdiet tellus. Duis dolor diam, posuere fermentum est in, convallis condimentum nisl. Suspendisse a nisl vitae velit accumsan pretium sed at quam. Aliquam tincidunt in odio in scelerisque.</p>\r\n<p>Nulla faucibus, est a interdum volutpat, sem neque interdum dui, aliquam accumsan velit sapien nec purus. Integer quis massa vel odio viverra molestie. Duis rhoncus posuere felis. Proin lobortis feugiat dui, eget posuere mauris aliquet ut. Integer sagittis lacinia varius. Aenean sit amet nunc mauris. Aenean sed lobortis justo, non pharetra justo.</p>'),
(7, '200_sunflowers_146748795.jpg', 'Sunflowers', 'Brighten Any Day', '22.95', '<p>Inspired by Vincent van Gogh, this arrangement of sunflowers will brighten anyone\'s day. It comes in an elegant turquoise stemmed vase.</p>\r\n<p> Nulla faucibus, est a interdum volutpat, sem neque interdum dui, aliquam accumsan velit sapien nec purus. Integer quis massa vel odio viverra molestie. Duis rhoncus posuere felis. Proin lobortis feugiat dui, eget posuere mauris aliquet ut. Integer sagittis lacinia varius. Aenean sit amet nunc mauris. Aenean sed lobortis justo, non pharetra justo.</p>\r\n<p>Ut lobortis elit ut lectus pretium blandit. In hac habitasse platea dictumst. Quisque euismod sit amet augue non malesuada. Etiam accumsan id tellus sed ullamcorper. Vivamus eros urna, auctor id pellentesque a, feugiat at dui. Vivamus sagittis porttitor euismod. Fusce vitae ante quis orci posuere aliquam. Nullam cursus erat eu vehicula volutpat. Maecenas ut magna risus. Nunc eu eleifend massa. </p>'),
(8, '200_white_tulip_163199928.jpg', 'White Tulips', 'Purely Beautiful', '19.95', '<p>Pure white flowers in a glass bowl. Simply elegant, simply beautiful, simply delightful.</p>\r\n<p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pulvinar arcu pulvinar, dictum turpis vel, semper risus. Curabitur ac augue et felis tempor molestie. Fusce ligula libero, dignissim eget ultrices ut, varius sit amet massa. Curabitur luctus nulla non lacus malesuada, eget elementum arcu lacinia. Fusce et metus non nulla sodales hendrerit. Aenean vitae enim nunc. Integer ultrices erat ac nunc commodo, in mattis mi viverra. Nullam et vehicula orci.</p>\r\n<p>Sed accumsan, odio at vestibulum viverra, magna magna cursus mi, a venenatis nibh enim sagittis felis. Suspendisse elit tortor, dictum a est in, sollicitudin laoreet purus. Nullam quis porta tortor. Suspendisse potenti. Suspendisse commodo pulvinar arcu nec fringilla. Pellentesque dignissim scelerisque elit, nec sollicitudin turpis sodales ut.</p>'),
(9, '200_tulips_daffodils_153986115.jpg', 'Mixed Tulips', 'Tea for Two', '15.95', '<p>A fun arrangement of spring flowers in two milk jugs. What a nice way to wish all the best to a happy couple on their engagement or wedding.</p>\r\n<p>Aenean non rhoncus nisi. Fusce non sem suscipit, posuere risus et, adipiscing ante. Maecenas nec neque ac urna bibendum viverra eu a eros. Maecenas quis eros a lorem blandit euismod sit amet venenatis leo. Praesent a justo ut turpis tristique volutpat. Sed volutpat felis eget enim laoreet, ac porttitor eros interdum.</p>\r\n<p>Praesent sit amet tempus metus. In porttitor rhoncus arcu eget blandit. Cras sagittis, dolor ut lacinia tempus, lectus nunc varius augue, ut pellentesque ante libero a justo. Donec non eros dui. Curabitur a dapibus enim. Nam fermentum, turpis ac laoreet rhoncus, arcu est accumsan est, a condimentum ligula nisl quis augue. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce ut hendrerit tellus, ac aliquet arcu. Praesent volutpat, mauris vitae feugiat ullamcorper, quam neque tristique risus, rhoncus tempus tellus metus imperdiet tellus.</p>'),
(10, '200_arrangement_94972439.jpg', 'Mixed Bouquet', 'Thinking of You', '35.95', '<p>A luxurious arrangement of flowers and greenery in a superior quality square vase. The perfect way to tell someone special that you\'re thinking of them.</p>\r\n<p> Sed accumsan, odio at vestibulum viverra, magna magna cursus mi, a venenatis nibh enim sagittis felis. Suspendisse elit tortor, dictum a est in, sollicitudin laoreet purus. Nullam quis porta tortor. Suspendisse potenti. Suspendisse commodo pulvinar arcu nec fringilla. Pellentesque dignissim scelerisque elit, nec sollicitudin turpis sodales ut. Sed eget elementum augue, non dapibus dui. Aenean non rhoncus nisi.</p>\r\n<p>Fusce non sem suscipit, posuere risus et, adipiscing ante. Maecenas nec neque ac urna bibendum viverra eu a eros. Maecenas quis eros a lorem blandit euismod sit amet venenatis leo. Praesent a justo ut turpis tristique volutpat. Sed volutpat felis eget enim laoreet, ac porttitor eros interdum. Praesent sit amet tempus metus. In porttitor rhoncus arcu eget blandit.</p>\r\n<p>Cras sagittis, dolor ut lacinia tempus, lectus nunc varius augue, ut pellentesque ante libero a justo. Donec non eros dui. Curabitur a dapibus enim. Nam fermentum, turpis ac laoreet rhoncus, arcu est accumsan est, a condimentum ligula nisl quis augue.</p>'),
(11, '200_irises_lilies_87478811.jpg', 'Irises and Lilies', 'Simply Elegant', '22.95', '<p>Irises and lilies are among the most elegant of flowers. Add some ferns for extra greenery, and you have a simply elegant arrangement at a very affordable price.</p>\r\n<p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce ut hendrerit tellus, ac aliquet arcu. Praesent volutpat, mauris vitae feugiat ullamcorper, quam neque tristique risus, rhoncus tempus tellus metus imperdiet tellus. Duis dolor diam, posuere fermentum est in, convallis condimentum nisl. Suspendisse a nisl vitae velit accumsan pretium sed at quam. Aliquam tincidunt in odio in scelerisque.</p>\r\n<p>Nulla faucibus, est a interdum volutpat, sem neque interdum dui, aliquam accumsan velit sapien nec purus. Integer quis massa vel odio viverra molestie. Duis rhoncus posuere felis. Proin lobortis feugiat dui, eget posuere mauris aliquet ut. Integer sagittis lacinia varius. Aenean sit amet nunc mauris. Aenean sed lobortis justo, non pharetra justo.</p>'),
(12, '200_pink_white_daisies_146806077.jpg', 'Pink and White Mums', 'Blush and Bashful', '19.95', '<p>Not quite sure how to say \"Sorry\"? Or maybe \"I love you\"? Save your blushes with this simple arrangement of pink and white crysanthemums.</p>\r\n<p> Sed accumsan, odio at vestibulum viverra, magna magna cursus mi, a venenatis nibh enim sagittis felis. Suspendisse elit tortor, dictum a est in, sollicitudin laoreet purus. Nullam quis porta tortor. Suspendisse potenti. Suspendisse commodo pulvinar arcu nec fringilla. Pellentesque dignissim scelerisque elit, nec sollicitudin turpis sodales ut. Sed eget elementum augue, non dapibus dui. Aenean non rhoncus nisi. Fusce non sem suscipit, posuere risus et, adipiscing ante. Maecenas nec neque ac urna bibendum viverra eu a eros. Maecenas quis eros a lorem blandit euismod sit amet venenatis leo. Praesent a justo ut turpis tristique volutpat.</p>\r\n<p>Sed volutpat felis eget enim laoreet, ac porttitor eros interdum. Praesent sit amet tempus metus. In porttitor rhoncus arcu eget blandit. Cras sagittis, dolor ut lacinia tempus, lectus nunc varius augue, ut pellentesque ante libero a justo. Donec non eros dui. Curabitur a dapibus enim. Nam fermentum, turpis ac laoreet rhoncus, arcu est accumsan est, a condimentum ligula nisl quis augue.</p>'),
(13, '200_tulips_watering_can_155465445.jpg', 'Tulips in Watering Can', 'Morning in the Garden', '29.95', '<p>A silver watering can overflowing with red and yellow tulips. What a way to say \"Top of the morning to you!\"</p>\r\n<p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pulvinar arcu pulvinar, dictum turpis vel, semper risus. Curabitur ac augue et felis tempor molestie. Fusce ligula libero, dignissim eget ultrices ut, varius sit amet massa. Curabitur luctus nulla non lacus malesuada, eget elementum arcu lacinia. Fusce et metus non nulla sodales hendrerit. Aenean vitae enim nunc. Integer ultrices erat ac nunc commodo, in mattis mi viverra. Nullam et vehicula orci.</p>\r\n<p>Sed accumsan, odio at vestibulum viverra, magna magna cursus mi, a venenatis nibh enim sagittis felis. Suspendisse elit tortor, dictum a est in, sollicitudin laoreet purus. Nullam quis porta tortor. Suspendisse potenti. Suspendisse commodo pulvinar arcu nec fringilla. Pellentesque dignissim scelerisque elit, nec sollicitudin turpis sodales ut.</p>'),
(14, '200_birthday_163167595.jpg', 'Orchid Bouquet', 'Orchids for the Table', '35.95', '<p>This is one for formal occasions, or to spoil someone who\'s really special. An exotic array of orchids in a deep red square vase.</p>\r\n<p>Donec non eros dui. Curabitur a dapibus enim. Nam fermentum, turpis ac laoreet rhoncus, arcu est accumsan est, a condimentum ligula nisl quis augue. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce ut hendrerit tellus, ac aliquet arcu. Praesent volutpat, mauris vitae feugiat ullamcorper, quam neque tristique risus, rhoncus tempus tellus metus imperdiet tellus. Duis dolor diam, posuere fermentum est in, convallis condimentum nisl. Suspendisse a nisl vitae velit accumsan pretium sed at quam. Aliquam tincidunt in odio in scelerisque.</p>\r\n<p>Nulla faucibus, est a interdum volutpat, sem neque interdum dui, aliquam accumsan velit sapien nec purus. Integer quis massa vel odio viverra molestie. Duis rhoncus posuere felis. Proin lobortis feugiat dui, eget posuere mauris aliquet ut. Integer sagittis lacinia varius. Aenean sit amet nunc mauris. Aenean sed lobortis justo, non pharetra justo.</p>'),
(15, '200_red_yellow_roses_119752732.jpg', 'Red and Yellow Roses', 'Classic Rose Bouquet', '49.95', '<p>For that special occasion, say it with roses. I love you. Happy anniversary. Congratulations. Whatever you want to say, roses are the perfect choice.</p>\r\n<p> Praesent sit amet tempus metus. In porttitor rhoncus arcu eget blandit. Cras sagittis, dolor ut lacinia tempus, lectus nunc varius augue, ut pellentesque ante libero a justo. Donec non eros dui. Curabitur a dapibus enim. Nam fermentum, turpis ac laoreet rhoncus, arcu est accumsan est, a condimentum ligula nisl quis augue.</p>\r\n<p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce ut hendrerit tellus, ac aliquet arcu. Praesent volutpat, mauris vitae feugiat ullamcorper, quam neque tristique risus, rhoncus tempus tellus metus imperdiet tellus. Duis dolor diam, posuere fermentum est in, convallis condimentum nisl. Suspendisse a nisl vitae velit accumsan pretium sed at quam. Aliquam tincidunt in odio in scelerisque. Nulla faucibus, est a interdum volutpat, sem neque interdum dui, aliquam accumsan velit sapien nec purus. Integer quis massa vel odio viverra molestie.</p>\r\n<p>Duis rhoncus posuere felis. Proin lobortis feugiat dui, eget posuere mauris aliquet ut. Integer sagittis lacinia varius. Aenean sit amet nunc mauris. Aenean sed lobortis justo, non pharetra justo.</p>'),
(16, '200_white_lily_pink_daisy_92493508.jpg', 'Lilies and Roses', 'Evening Surprise', '29.95', '<p>An unconventional mix of lilies, roses, and crysanthemums. Surprise your loved one with this unique arrangement.</p>\r\n<p>Duis rhoncus posuere felis. Proin lobortis feugiat dui, eget posuere mauris aliquet ut. Integer sagittis lacinia varius. Aenean sit amet nunc mauris. Aenean sed lobortis justo, non pharetra justo. Ut lobortis elit ut lectus pretium blandit. In hac habitasse platea dictumst.</p>\r\n<p>Quisque euismod sit amet augue non malesuada. Etiam accumsan id tellus sed ullamcorper. Vivamus eros urna, auctor id pellentesque a, feugiat at dui. Vivamus sagittis porttitor euismod. Fusce vitae ante quis orci posuere aliquam. Nullam cursus erat eu vehicula volutpat. Maecenas ut magna risus. Nunc eu eleifend massa.</p>'),
(17, '200_carnations_daisies_92007328.jpg', 'Carnations and Daisies', 'Cheer Up!', '19.95', '<p>Carnations, daisies, and splashes of greenery&mdash;the perfect pick-me-up for someone feeling under the weather or just down in the dumps.</p>\r\n<p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pulvinar arcu pulvinar, dictum turpis vel, semper risus. Curabitur ac augue et felis tempor molestie. Fusce ligula libero, dignissim eget ultrices ut, varius sit amet massa. Curabitur luctus nulla non lacus malesuada, eget elementum arcu lacinia. Fusce et metus non nulla sodales hendrerit. Aenean vitae enim nunc. Integer ultrices erat ac nunc commodo, in mattis mi viverra. Nullam et vehicula orci.</p>\r\n<p>Sed accumsan, odio at vestibulum viverra, magna magna cursus mi, a venenatis nibh enim sagittis felis. Suspendisse elit tortor, dictum a est in, sollicitudin laoreet purus. Nullam quis porta tortor. Suspendisse potenti. Suspendisse commodo pulvinar arcu nec fringilla. Pellentesque dignissim scelerisque elit, nec sollicitudin turpis sodales ut. Sed eget elementum augue, non dapibus dui.</p>'),
(18, '200_purple_daisy_rose104274224.jpg', 'Daisy Bouquet', 'Purple Galore', '21.95', '<p>A vibrant mix of purple and white daisies, topped off with red roses. Delivered in a matching purple mosaic vase.</p>\r\n<p>Aenean non rhoncus nisi. Fusce non sem suscipit, posuere risus et, adipiscing ante. Maecenas nec neque ac urna bibendum viverra eu a eros. Maecenas quis eros a lorem blandit euismod sit amet venenatis leo. Praesent a justo ut turpis tristique volutpat. Sed volutpat felis eget enim laoreet, ac porttitor eros interdum.</p>\r\n<p>Praesent sit amet tempus metus. In porttitor rhoncus arcu eget blandit. Cras sagittis, dolor ut lacinia tempus, lectus nunc varius augue, ut pellentesque ante libero a justo. Donec non eros dui. Curabitur a dapibus enim. Nam fermentum, turpis ac laoreet rhoncus, arcu est accumsan est, a condimentum ligula nisl quis augue. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce ut hendrerit tellus, ac aliquet arcu.</p>'),
(19, '200_colorful_gerbera_119722776.jpg', 'Mixed Gerbera Daisies', 'Dotted Daisies', '25.95', '<p>This fun arrangement of gerbera daisies in round red vase with white polka dots is bound to brighten up anyone\'s day.</p>\r\n<p>Praesent volutpat, mauris vitae feugiat ullamcorper, quam neque tristique risus, rhoncus tempus tellus metus imperdiet tellus. Duis dolor diam, posuere fermentum est in, convallis condimentum nisl. Suspendisse a nisl vitae velit accumsan pretium sed at quam. Aliquam tincidunt in odio in scelerisque.</p>\r\n<p>Nulla faucibus, est a interdum volutpat, sem neque interdum dui, aliquam accumsan velit sapien nec purus. Integer quis massa vel odio viverra molestie. Duis rhoncus posuere felis. Proin lobortis feugiat dui, eget posuere mauris aliquet ut. Integer sagittis lacinia varius. Aenean sit amet nunc mauris. Aenean sed lobortis justo, non pharetra justo.</p>'),
(20, '200_yellow_white_mums_147664285.jpg', 'Daisy Mix', 'Patio Picnicking', '19.95', '<p>A simple, yet delightful arrangement of daisies and crystanthemums, just like a breath of fresh air. Ideal for the patio table or to bring the joys of nature indoors.</p>\r\n<p>Nullam quis porta tortor. Suspendisse potenti. Suspendisse commodo pulvinar arcu nec fringilla. Pellentesque dignissim scelerisque elit, nec sollicitudin turpis sodales ut. Sed eget elementum augue, non dapibus dui. Aenean non rhoncus nisi. Fusce non sem suscipit, posuere risus et, adipiscing ante. Maecenas nec neque ac urna bibendum viverra eu a eros. Maecenas quis eros a lorem blandit euismod sit amet venenatis leo. Praesent a justo ut turpis tristique volutpat. Sed volutpat felis eget enim laoreet, ac porttitor eros interdum.</p>\r\n<p>Praesent sit amet tempus metus. In porttitor rhoncus arcu eget blandit. Cras sagittis, dolor ut lacinia tempus, lectus nunc varius augue, ut pellentesque ante libero a justo. Donec non eros dui. Curabitur a dapibus enim. Nam fermentum, turpis ac laoreet rhoncus, arcu est accumsan est, a condimentum ligula nisl quis augue. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce ut hendrerit tellus, ac aliquet arcu. Praesent volutpat, mauris vitae feugiat ullamcorper, quam neque tristique risus, rhoncus tempus tellus metus imperdiet tellus.</p>'),
(21, '200_tulips_daffodils2_153986183.jpg', 'Mixed Tulips', 'Box of Happiness', '29.95', '<p>An explosion of color, with daffs and tulips in a yellow vase with a mosaic pattern. Sure to bring a happy smile to anyone\'s face.</p>\r\n<p> Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce ut hendrerit tellus, ac aliquet arcu. Praesent volutpat, mauris vitae feugiat ullamcorper, quam neque tristique risus, rhoncus tempus tellus metus imperdiet tellus. Duis dolor diam, posuere fermentum est in, convallis condimentum nisl. Suspendisse a nisl vitae velit accumsan pretium sed at quam. Aliquam tincidunt in odio in scelerisque.</p>\r\n<p>Nulla faucibus, est a interdum volutpat, sem neque interdum dui, aliquam accumsan velit sapien nec purus. Integer quis massa vel odio viverra molestie. Duis rhoncus posuere felis. Proin lobortis feugiat dui, eget posuere mauris aliquet ut. Integer sagittis lacinia varius. Aenean sit amet nunc mauris. Aenean sed lobortis justo, non pharetra justo.</p>'),
(22, '200_butterflies_120624479.jpg', 'Daisies and Butterflies', 'Bounty of Butterflies', '25.95', '<p>We supply the flowers, and the butterflies are sure to gather round this delightful mix of wild flowers. Just like an English country garden in an elegant vase.</p>\r\n<p>Suspendisse potenti. Suspendisse commodo pulvinar arcu nec fringilla. Pellentesque dignissim scelerisque elit, nec sollicitudin turpis sodales ut. Sed eget elementum augue, non dapibus dui. Aenean non rhoncus nisi. Fusce non sem suscipit, posuere risus et, adipiscing ante. Maecenas nec neque ac urna bibendum viverra eu a eros. Maecenas quis eros a lorem blandit euismod sit amet venenatis leo. Praesent a justo ut turpis tristique volutpat. Sed volutpat felis eget enim laoreet, ac porttitor eros interdum.</p>\r\n<p>Donec non eros dui. Curabitur a dapibus enim. Nam fermentum, turpis ac laoreet rhoncus, arcu est accumsan est, a condimentum ligula nisl quis augue. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce ut hendrerit tellus, ac aliquet arcu. Praesent volutpat, mauris vitae feugiat ullamcorper, quam neque tristique risus, rhoncus tempus tellus metus imperdiet tellus. Duis dolor diam, posuere fermentum est in, convallis condimentum nisl. Suspendisse a nisl vitae velit accumsan pretium sed at quam.</p>'),
(23, '200_tulips_irises_121357306.jpg', 'Irises and Tulips', 'Mardi Gras Mambo', '29.95', '<p>A flamboyant mix of irises and yellow tulips, this arrangement will set your table dancing to a whole new rhythm.</p>\r\n<p>Fusce ligula libero, dignissim eget ultrices ut, varius sit amet massa. Curabitur luctus nulla non lacus malesuada, eget elementum arcu lacinia. Fusce et metus non nulla sodales hendrerit. Aenean vitae enim nunc. Integer ultrices erat ac nunc commodo, in mattis mi viverra. Nullam et vehicula orci.</p>\r\n<p>Sed accumsan, odio at vestibulum viverra, magna magna cursus mi, a venenatis nibh enim sagittis felis. Suspendisse elit tortor, dictum a est in, sollicitudin laoreet purus. Nullam quis porta tortor. Suspendisse potenti. Suspendisse commodo pulvinar arcu nec fringilla. Pellentesque dignissim scelerisque elit, nec sollicitudin turpis sodales ut. Sed eget elementum augue, non dapibus dui.</p>'),
(24, '200_tulips_daffodils4_160232631.jpg', 'Mixed Bulbs', 'Cascade of Color', '32.95', '<p>Gorgeous, exuberant, a riot of color... Go completely wild with this stunning arrangement of flowers in season.</p>\r\n<p> Nulla faucibus, est a interdum volutpat, sem neque interdum dui, aliquam accumsan velit sapien nec purus. Integer quis massa vel odio viverra molestie. Duis rhoncus posuere felis. Proin lobortis feugiat dui, eget posuere mauris aliquet ut. Integer sagittis lacinia varius. Aenean sit amet nunc mauris. Aenean sed lobortis justo, non pharetra justo.</p>\r\n<p>Ut lobortis elit ut lectus pretium blandit. In hac habitasse platea dictumst. Quisque euismod sit amet augue non malesuada. Etiam accumsan id tellus sed ullamcorper. Vivamus eros urna, auctor id pellentesque a, feugiat at dui. Vivamus sagittis porttitor euismod. Fusce vitae ante quis orci posuere aliquam. Nullam cursus erat eu vehicula volutpat.</p>');

-- --------------------------------------------------------

--
-- Struktur-dump for tabellen `flowers`
--

CREATE TABLE `flowers` (
  `FID` int(11) NOT NULL,
  `FName` varchar(100) NOT NULL,
  `FClass` varchar(100) NOT NULL,
  `FDesc` varchar(2000) NOT NULL,
  `FImg` varchar(100) NOT NULL,
  `FAlttxt` varchar(200) NOT NULL,
  `FPrice` tinyint(4) NOT NULL,
  `FStock` int(11) NOT NULL,
  `FSold` int(11) NOT NULL,
  `FColors` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Data dump for tabellen `flowers`
--

INSERT INTO `flowers` (`FID`, `FName`, `FClass`, `FDesc`, `FImg`, `FAlttxt`, `FPrice`, `FStock`, `FSold`, `FColors`) VALUES
(1, 'Calla Lily', 'Lily', '<p>Zantedeschia aethiopica, commonly known as calla lily and arum lily, is a species in the family Araceae, native to southern Africa in Lesotho, South Africa, and Swaziland</p><p>Zantedeschia aethiopica is a rhizomatous herbaceous perennial plant, evergreen where rainfall and temperatures are adequate, deciduous where there is a dry season. Its preferred habitat is in streams and ponds or on the banks. It grows to 0.6-1 m (2.0-3.3 ft) tall, with large clumps of broad, arrow shaped dark green leaves up to 45 cm (18 in) long. The inflorescences are large and are produced in spring, summer and autumn, with a pure white spathe up to 25 cm (9.8 in) and a yellow spadix up to 90 mm (3.5 in) long. The spadix produces a faint, sweet fragrance.</p><p>Zantedeschia aethiopica is the national flower of the island nation of Saint Helena, where it grows widely. Further, it is an important symbol of Irish republicanism and nationalism since 1926, because it is used to commemorate the dead of Easter 1916 and onward.</p>', '160_calla_blush_160337318.jpg', 'Calla Lilies', 3, 300, 10500, 'Blush Yellow Pink Purple'),
(2, 'Sunflower', 'Asterales', '<p>Helianthus (/ˌhiːliˈænθəs/) is a genus comprising about 70 species of annual and perennial flowering plants in the daisy family Asteraceae. Except for three South American species, the species of Helianthus are native to North America and Central America. The common names \"sunflower\" and \"common sunflower\" typically refer to the popular annual species Helianthus annuus, whose round flower heads in combination with the ligules look like the sun. This and other species, notably Jerusalem artichoke (H. tuberosus), are cultivated in temperate regions and some tropical regions as food crops for humans, cattle, and poultry, and as ornamental plants. The species H. annuus typically grows during the summer and into early fall, with the peak growth season being mid-summer.</p><p>Several perennial Helianthus species are grown in gardens, but have a tendency to spread rapidly and can become aggressive. The whorled sunflower, Helianthus verticillatus, was listed as an endangered species in 2014 when the U.S. Fish and Wildlife Service issued a final rule protecting it under the Endangered Species Act. The primary threats are industrial forestry and pine plantations in Alabama, Georgia, and Tennessee. They grow to 1.8 m (6 ft) and are primarily found in woodlands, adjacent to creeks and moist, prairie-like areas.</p>', '160_sunflower_146748795.jpg', 'Sunflowers', 3, 780, 150342, 'Yellow'),
(3, 'Iris', 'Iris', '<p>Iris is a genus of 260–300 species of flowering plants with showy flowers. It takes its name from the Greek word for a rainbow, which is also the name for the Greek goddess of the rainbow, Iris. Some authors state that the name refers to the wide variety of flower colors found among the many species. As well as being the scientific name, iris is also widely used as a common name for all Iris species, as well as some belonging to other closely related genera. A common name for some species is \'flags\', while the plants of the subgenus Scorpiris are widely known as \'junos\', particularly in horticulture. It is a popular garden flower.</p><p>The often-segregated, monotypic genera Belamcanda (blackberry lily, I. domestica), Hermodactylus (snake\'s head iris, I. tuberosa), and Pardanthopsis (vesper iris, I. dichotoma) are currently included in Iris.</p><p>Three Iris varieties are used in the Iris flower data set outlined by Ronald Fisher in his 1936 paper The use of multiple measurements in taxonomic problems as an example of linear discriminant analysis.</p>', '160_iris_purple_121549009.jpg', 'Iris', 2, 340, 65154, 'Purple'),
(4, 'Peruvian Lily', 'Lily', '<p>Alstroemeria (/ˌælstrɪˈmɪəriə/), commonly called the Peruvian lily or lily of the Incas, is a genus of flowering plants in the family Alstroemeriaceae. They are all native to South America although some have become naturalized in the United States, Mexico, Australia, New Zealand, Madeira and the Canary Islands. Almost all of the species are restricted to one of two distinct centers of diversity, one in central Chile, the other in eastern Brazil. Species of Alstroemeria from Chile are winter-growing plants while those of Brazil are summer-growing. All are long-lived perennials except A. graminea, a diminutive annual from the Atacama Desert of Chile.</p><p>Plants of this genus grow from a cluster of tubers. They send up fertile and sterile stems, the fertile stems of some species reaching 1.5 meters in height. The leaves are alternately arranged and resupinate, twisted on the petioles so that the undersides face up. The leaves are variable in shape and the blades have smooth edges. The flowers are solitary or borne in umbels. The flower has six petals each up to 5 centimeters long. They come in many shades of red, orange, purple, green, and white, flecked and striped and streaked with darker colors. There are six curving stamens. The stigma has three lobes. The fruit is a capsule with three valves. Alstroemeria are classified as an inferior monocot, meaning the petals are located above the ovary and the leaves are parallel.</p>', '160_alstromeria_87519333.jpg', 'Peruvian Lilies', 2, 120, 430, 'Pink/White'),
(5, 'Daffodil', 'Amaryllis', '<p>Narcissus is a genus of predominantly spring flowering perennial plants of the amaryllis family, Amaryllidaceae. Various common names including daffodil, narcissus and jonquil are used to describe all or some members of the genus. Narcissus has conspicuous flowers with six petal-like tepals surmounted by a cup- or trumpet-shaped corona. The flowers are generally white or yellow (also orange or pink in garden varieties), with either uniform or contrasting coloured tepals and corona.</p><p>Narcissus were well known in ancient civilisation, both medicinally and botanically, but formally described by Linnaeus in his Species Plantarum (1753). The genus is generally considered to have about ten sections with approximately 50 species. The number of species has varied, depending on how they are classified, due to similarity between species and hybridisation. The genus arose some time in the Late Oligocene to Early Miocene epochs, in the Iberian peninsula and adjacent areas of southwest Europe. The exact origin of the name Narcissus is unknown, but it is often linked to a Greek word for intoxicated (narcotic) and the myth of the youth of that name who fell in love with his own reflection. The English word \"daffodil\" appears to be derived from \"asphodel\", with which it was commonly compared.</p><p>The species are native to meadows and woods in southern Europe and North Africa with a centre of diversity in the Western Mediterranean, particularly the Iberian peninsula. Both wild and cultivated plants have naturalised widely, and were introduced into the Far East prior to the tenth century. Narcissi tend to be long-lived bulbs, which propagate by division, but are also insect-pollinated. Known pests, diseases and disorders include viruses, fungi, the larvae of flies, mites and nematodes. Some Narcissus species have become extinct, while others are threatened by increasing urbanisation and tourism. </p>', '160_daffodil_122442732.jpg', 'Daffodils', 2, 14530, 354216, 'Yellow'),
(6, 'Gerbera', 'Daisy', '<p>Gerbera (/ˈdʒɜːrbərə/ or /ˈɡɜːrbərə/) L. is a genus of plants in the Asteraceae (daisy family). It was named in honour of German botanist and medical doctor Traugott Gerber (1710-1743) who travelled extensively in Russia and was a friend of Carl Linnaeus.</p><p>Gerbera is native to tropical regions of South America, Africa and Asia. The first scientific description of a Gerbera was made by J.D. Hooker in Curtis\'s Botanical Magazine in 1889 when he described Gerbera jamesonii, a South African species also known as Transvaal daisy or Barberton daisy. Gerbera is also commonly known as the African daisy.</p><p>Gerbera species bear a large capitulum with striking, two-lipped ray florets in yellow, orange, white, pink or red colours. The capitulum, which has the appearance of a single flower, is actually composed of hundreds of individual flowers. The morphology of the flowers varies depending on their position in the capitulum. The flower heads can be as small as 7 cm (Gerbera mini \'Harley\') in diameter or up to 12 cm (Gerbera ‘Golden Serena’).</p><p>Gerbera is very popular and widely used as a decorative garden plant or as cut flowers. The domesticated cultivars are mostly a result of a cross between Gerbera jamesonii and another South African species Gerbera viridifolia. The cross is known as Gerbera hybrida. Thousands of cultivars exist. They vary greatly in shape and size. Colours include white, yellow, orange, red, and pink. The centre of the flower is sometimes black. Often the same flower can have petals of several different colours.</p><p>Gerbera is also important commercially. It is the fifth most used cut flower in the world (after rose, carnation, chrysanthemum, and tulip). It is also used as a model organism in studying flower formation.</p><p>Gerbera contains naturally occurring coumarin derivatives. Gerbera is a tender perennial plant. It is attractive to bees, butterflies, and birds, but resistant to deer. Small ones are called gerbrinis.</p>', '160_gerbera_purple_146798391.jpg', 'Gerbera', 3, 234, 1250, 'Purple Orange Pink Yellow'),
(7, 'Dendrobium', 'Orchid', '<p>Dendrobium is a genus of mostly epiphytic and lithophytic orchids in the family Orchidaceae. It is a very large genus, containing more than 1,800 species that are found in diverse habitats throughout much of south, east and southeast Asia, including China, Japan, India, the Philippines, Indonesia, Australia, New Guinea, Vietnam and many of the islands of the Pacific. Orchids in this genus have roots that creep over the surface of trees or rocks, rarely having their roots in soil. Up to six leaves develop in a tuft at the tip of a shoot and from one to a large number of flowers are arranged along an unbranched flowering stem. Several attempts have been made to separate Dendrobium into smaller genera, but most have not been accepted by the World Checklist of Selected Plant Families.</p><p>Dendrobium species are mostly epiphytic, or lithophytic although a few species are terrestrial. They are sympodial herbs with cylindrical roots usually arising from the base of a pseudobulb. The pseudobulbs, when present, are hard, sometimes cane-like, cylindrical or cone-shaped and more or less covered with the bases of the leaves. There are from one to many leaves arranged in two ranks, the leaves varying in shape from linear to oblong, sometimes cylindrical but never channelled or grooved. They are usually much longer than wide and last for only a single season.</p><p>Between one and a large number of resupinate or non-resupinate flowers are arranged along an unbranched flowering stem and may be short or long-lived. The flowers may be white, green, yellow, or pink to purple, often with contrasting colours in the labellum. The sepals and petals are usually free from and more or less similar to each other but markedly different from the labellum. The labellum is more or less egg-shaped, with the narrower end towards the base and flanks the column. There is often a callus consisting of narrow, parallel ridges, in the centre of the labellum.</p>', '160_dendrobium2_152158743.jpg', 'Dendrobium', 4, 60, 460, 'White/purple'),
(8, 'Rose', 'Rosa', '<p>A rose is a woody perennial flowering plant of the genus Rosa, in the family Rosaceae, or the flower it bears. There are over three hundred species and tens of thousands of cultivars. They form a group of plants that can be erect shrubs, climbing, or trailing, with stems that are often armed with sharp prickles. Flowers vary in size and shape and are usually large and showy, in colours ranging from white through yellows and reds. Most species are native to Asia, with smaller numbers native to Europe, North America, and northwestern Africa. Species, cultivars and hybrids are all widely grown for their beauty and often are fragrant. Roses have acquired cultural significance in many societies. Rose plants range in size from compact, miniature roses, to climbers that can reach seven meters in height. Different species hybridize easily, and this has been used in the development of the wide range of garden roses.</p><p>The name rose comes from French, itself from Latin rosa, which was perhaps borrowed from Oscan, from Greek ρόδον rhódon (Aeolic βρόδον wródon), itself borrowed from Old Persian wrd- (wurdi), related to Avestan varəδa, Sogdian ward, Parthian wâr</p><p>The leaves are borne alternately on the stem. In most species they are 5 to 15 centimetres (2.0 to 5.9 in) long, pinnate, with (3–) 5–9 (–13) leaflets and basal stipules; the leaflets usually have a serrated margin, and often a few small prickles on the underside of the stem. Most roses are deciduous but a few (particularly from Southeast Asia) are evergreen or nearly so.</p><p>The flowers of most species have five petals, with the exception of Rosa sericea, which usually has only four. Each petal is divided into two distinct lobes and is usually white or pink, though in a few species yellow or red. Beneath the petals are five sepals (or in the case of some Rosa sericea, four). These may be long enough to be visible when viewed from above and appear as green points alternating with the rounded petals.</p>', '160_rose_pink_112277154.jpg', 'Rose Pink', 3, 25000, 1543250, 'Pink Peach White Yellow Red'),
(9, 'Lily', 'Lily', '<p>Lilium (members of which are true lilies) is a genus of herbaceous flowering plants growing from bulbs, all with large prominent flowers. Lilies are a group of flowering plants which are important in culture and literature in much of the world. Most species are native to the temperate northern hemisphere, though their range extends into the northern subtropics. Many other plants have \"lily\" in their common name but are not related to true lilies. </p><p>Lilies are tall perennials ranging in height from 2–6 ft (60–180 cm). They form naked or tunicless scaly underground bulbs which are their organs of perennation. In some North American species the base of the bulb develops into rhizomes, on which numerous small bulbs are found. Some species develop stolons. Most bulbs are buried deep in the ground, but a few species form bulbs near the soil surface. Many species form stem-roots. With these, the bulb grows naturally at some depth in the soil, and each year the new stem puts out adventitious roots above the bulb as it emerges from the soil. These roots are in addition to the basal roots that develop at the base of the bulb.</p><p>The flowers are large, often fragrant, and come in a wide range of colors including whites, yellows, oranges, pinks, reds and purples. Markings include spots and brush strokes. The plants are late spring- or summer-flowering. Flowers are borne in racemes or umbels at the tip of the stem, with six tepals spreading or reflexed, to give flowers varying from funnel shape to a \"Turk\'s cap\". The tepals are free from each other, and bear a nectary at the base of each flower. The ovary is \'superior\', borne above the point of attachment of the anthers. The fruit is a three-celled capsule.</p><p>Seeds ripen in late summer. They exhibit varying and sometimes complex germination patterns, many adapted to cool temperate climates.</p><p>Naturally most cool temperate species are deciduous and dormant in winter in their native environment.</p>', '160_lily_pink_160102549.jpg', 'Lily Pink', 3, 1450, 16320, 'Pink Red White Yellow Orange'),
(10, 'Tulip', 'Tulipa', '<p>Tulips (Tulipa) form a genus of spring-blooming perennial herbaceous bulbiferous geophytes (having bulbs as storage organs). The flowers are usually large, showy and brightly colored, generally red, pink, yellow, or white (usually in warm colors). They often have a different colored blotch at the base of the tepals (petals and sepals, collectively), internally. Because of a degree of variability within the populations, and a long history of cultivation, classification has been complex and controversial. The tulip is a member of the lily family, Liliaceae, along with 14 other genera, where it is most closely related to Amana, Erythronium and Gagea in the tribe Lilieae. There are about 75 species, and these are divided among four subgenera. The name \"tulip\" is thought to be derived from a Persian word for turban, which it may have been thought to resemble. Tulips originally were found in a band stretching from Southern Europe to Central Asia, but since the seventeenth century have become widely naturalised and cultivated (see map). In their natural state they are adapted to steppes and mountainous areas with temperate climates. Flowering in the spring, they become dormant in the summer once the flowers and leaves die back, emerging above ground as a shoot from the underground bulb in early spring.</p><p>Originally growing wild in the valleys of the Tian Shan Mountains, tulips were cultivated in Constantinople as early as 1055. By the 15th century, tulips were among the most prized flowers; becoming the symbol of the Ottomans.</p><p>While tulips had probably been cultivated in Persia from the tenth century, they did not come to the attention of the West until the sixteenth century, when Western diplomats to the Ottoman court observed and reported on them. They were rapidly introduced into Europe and became a frenzied commodity during Tulip mania.</p>', '160_tulip_purple_160910481.jpg', 'Tulip Purple', 2, 46500, 145650, 'Purple Yellow Golden Pink Red'),
(11, 'Lilac', 'Oleaceae', '<p>Syringa vulgaris (lilac or common lilac) is a species of flowering plant in the olive family Oleaceae, native to the Balkan Peninsula, where it grows on rocky hills. Grown for its scented purple flowers in spring, this large shrub or small tree is widely cultivated and has been naturalized in parts of Europe and North America. It is not regarded as an aggressive species, found in the wild in widely scattered sites, usually in the vicinity of past or present human habitations.</p><p>Syringa vulgaris is a large deciduous shrub or multistemmed small tree, growing to 6–7 m (20–23 ft) high. It produces secondary shoots (suckers) from the base or roots, with stem diameters up to 20 cm (8 in), which in the course of decades may produce a small clonal thicket. The bark is grey to grey-brown, smooth on young stems, longitudinally furrowed, and flaking on older stems. The leaves are simple, 4–12 cm (2–5 in) and 3–8 cm broad, light green to glaucous, oval to cordate, with pinnate leaf venation, a mucronate apex, and an entire margin. They are arranged in opposite pairs or occasionally in whorls of three. The flowers have a tubular base to the corolla 6–10 mm long with an open four-lobed apex 5–8 mm across, usually lilac to mauve, occasionally white. They are arranged in dense, terminal panicles 8–18 cm (3–7 in) long. The fruit is a dry, smooth, brown capsule, 1–2 cm long, splitting in two to release the two-winged seeds.</p>', '160_lilac_157045915.jpg', 'Lilac', 4, 120, 346, 'Purple'),
(12, 'Daisy', 'Daisy', '<p>Bellis perennis is a common European species of daisy, of the family Asteraceae, often considered the archetypal species of that name.</p><p>Many related plants also share the name \"daisy\", so to distinguish this species from other daisies it is sometimes qualified as common daisy, lawn daisy or English daisy. Historically, it has also been commonly known as bruisewort and occasionally woundwort (although the common name woundwort is now more closely associated with Stachys). Bellis perennis is native to western, central and northern Europe, including remote islands such as the Faroe Islands but widely naturalised in most temperate regions including the Americas and Australasia. </p><p>It is a perennial herbaceous plant with short creeping rhizomes and rosettes of small rounded or spoon-shaped leaves that are from 3/4 to 2 inches (approx. 2–5 cm) long and grow flat to the ground. The species habitually colonises lawns, and is difficult to eradicate by mowing – hence the term \'lawn daisy\'. It exhibits the phenomenon of heliotropism where the flowers follow the position of the sun in the sky.</p><p>The flowerheads are composite, in the form of a pseudanthium, consisting of many sessile flowers about 3/4 to 1-1/4 in (approx. 2–3 cm) in diameter, with white ray florets (often tipped red) and yellow disc florets. Each inflorescence is borne on single leafless stems 3/4 – 4 in (approx. 2–10 cm), rarely 6 in (approx. 15 cm) tall. The capitulum, or disc of florets, is surrounded by two rows of green bracts known as \"phyllaries\". The achenes are without pappus.</p>', '160_daisy_white_159207232.jpg', 'Daisy White', 1, 25000, 400000, 'White'),
(13, 'Phalaenopsis', 'Orchid', '<p>Phalaenopsis /ˌfælɪˈnɒpsɪs/ Blume (1825), commonly known as moth orchids, is a genus of about seventy species of plants in the family Orchidaceae. Orchids in this genus are monopodial epiphytes or lithophytes with long, coarse roots, short, leafy stems and long-lasting, flat flowers arranged in a flowering stem that often branches near the end. Orchids in this genus are native to India, Taiwan, China, Southeast Asia, New Guinea and Australia with the majority in Indonesia and the Philippines.</p><p>Orchids in the genus Phalaenopsis are monopodial epiphytic, sometimes lithophytic herbs with long, coarse roots and short leafy stems hidden by overlapping leaf bases. The leaves are usually arranged in two rows, relatively large and leathery, oblong to elliptic and sometimes succulent. A few to many, small to large, long-lasting, flat, often fragrant flowers are arranged on erect to hanging racemes or panicles. The sepals and petals are free from and spread widely apart from each other. The lateral sepals are usually larger than the dorsal sepal and the petals much wider than the sepals. The labellum is joined stiffly to the column and has three lobes. The side lobes are erect and more or less parallel to each other and the middle lobe sometimes has a pair of appendages or antennae.</p>', '200_phalaenopsis_164373689.jpg', 'Phalaenopsis', 4, 400, 1620, 'Purple Pink White'),
(14, 'Oncidium', 'Orchid', '<p>Oncidium, abbreviated as Onc. in the horticultural trade, is a genus that contains about 330 species of orchids from the subtribe Oncidiinae of the orchid family (Orchidaceae). As presently conceived (May 2014), it is distributed across much of South America, Central America, Mexico and the West Indies, with one species (O. ensatum) extending into Florida.Common names for plants in this genus include dancing-lady orchid and golden shower orchid.</p><p>This genus was first described by Olof Swartz in 1800 with the orchid Oncidium altissimum, which has become the type species. Its name is derived from the Greek word ὀγκος, \"onkos\", meaning \"swelling\". This refers to the callus at the lower lip.</p><p>Most species in the Oncidium genus are epiphytes, although some are lithophytes or terrestrials. They are widespread from northern Mexico, the Caribbean, and some parts of South Florida to South America. They usually occur in seasonally dry areas.</p>', '200_oncidium2_152176782.jpg', 'Oncidium', 4, 125, 357, 'Yellow White/pink Red'),
(15, 'Cattleya', 'Orchid', '<p>Cattleya (/ˈkætliə/) is a genus of orchids from Costa Rica south to Argentina. The genus is abbreviated C in trade journals.</p><p>Epiphytic or terrestrial orchids with cylindrical rhizome from which the fleshy noodle-like roots grow. Pseudobulbs can be conical, spindle-shaped or cylindrical; with upright growth; one or two leaves growing from the top of them. The leaves can be oblong, lanceolate or elliptical, somewhat fleshy, with smooth margin. The inflorescence is a terminal raceme with few or several flowers. Flowers have sepals and petals free from each other; the lip or labellum (lowermost petal), usually has a different coloration and shape from the rest of the flower and covers in part the flower column forming a tube. There are four polliniums (bag-like organs that contain pollen). The fruit is a capsule with many small seeds.</p>', '200_cattleya2_149067833.jpg', 'Cattleya', 4, 54, 287, 'Yellow Pink White Purple');

--
-- Begrænsninger for dumpede tabeller
--

--
-- Indeks for tabel `arrangements`
--
ALTER TABLE `arrangements`
  ADD PRIMARY KEY (`id`);

--
-- Indeks for tabel `flowers`
--
ALTER TABLE `flowers`
  ADD PRIMARY KEY (`FID`);

--
-- Brug ikke AUTO_INCREMENT for slettede tabeller
--

--
-- Tilføj AUTO_INCREMENT i tabel `arrangements`
--
ALTER TABLE `arrangements`
  MODIFY `id` smallint(5) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=25;

--
-- Tilføj AUTO_INCREMENT i tabel `flowers`
--
ALTER TABLE `flowers`
  MODIFY `FID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=16;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
